# Generated by Django 4.0.4 on 2022-04-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='category',
            field=models.CharField(choices=[('User', 'User'), ('mission', 'mission'), ('etc', 'etc')], default='mission', max_length=30),
        ),
    ]
